// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcU0M94kcdRD1tvT0Vgeeg5fuWlGVoZK0',
    appId: '1:706472457634:web:16482d5afb2ba31febaefb',
    messagingSenderId: '706472457634',
    projectId: 'atal-without-krishna',
    authDomain: 'atal-without-krishna.firebaseapp.com',
    storageBucket: 'atal-without-krishna.firebasestorage.app',
    measurementId: 'G-2FYCR87VKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDZkDIPXmGrVTH8a5xNWlf6R59EoPi1M',
    appId: '1:706472457634:android:35c8417278bfc187ebaefb',
    messagingSenderId: '706472457634',
    projectId: 'atal-without-krishna',
    storageBucket: 'atal-without-krishna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-nfs73G-qEF055fxdMMZWGWal_rBNvM',
    appId: '1:706472457634:ios:7861d774da22260cebaefb',
    messagingSenderId: '706472457634',
    projectId: 'atal-without-krishna',
    storageBucket: 'atal-without-krishna.firebasestorage.app',
    iosBundleId: 'com.yskrishna.atalwithoutkrishna.atalWithoutKrishna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-nfs73G-qEF055fxdMMZWGWal_rBNvM',
    appId: '1:706472457634:ios:7861d774da22260cebaefb',
    messagingSenderId: '706472457634',
    projectId: 'atal-without-krishna',
    storageBucket: 'atal-without-krishna.firebasestorage.app',
    iosBundleId: 'com.yskrishna.atalwithoutkrishna.atalWithoutKrishna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcU0M94kcdRD1tvT0Vgeeg5fuWlGVoZK0',
    appId: '1:706472457634:web:919b807eda49876cebaefb',
    messagingSenderId: '706472457634',
    projectId: 'atal-without-krishna',
    authDomain: 'atal-without-krishna.firebaseapp.com',
    storageBucket: 'atal-without-krishna.firebasestorage.app',
    measurementId: 'G-11YP3WV309',
  );
}
